### ISSUE TITLE
ban info 

### ISSUE THREAD

**Issue by 0x17Bb1** [Upikk/Fiveguard_Discordbot#1]
getting the ban resone is not working only prints Results mabey you dit not print the right think ? 
![Screenshot 2023-07-03 214701](https://github.com/Upikk/Fiveguard_Discordbot/assets/125394012/07880e02-0c7d-4cf9-b9ed-211a104834a5)

**Comment by Upikk** [comment]
hello, this has been fixed 3 minutes ago 👍 , sorry for the problem

**Comment by Upikk** [comment]
> getting the ban resone is not working only prints Results mabey you dit not print the right think ? ![Screenshot 2023-07-03 214701](https://user-images.githubusercontent.com/125394012/250649381-07880e02-0c7d-4cf9-b9ed-211a104834a5.png)

hello, this has been fixed 3 minutes ago 👍 , sorry for the problem
